name: LaTeX Compilation

on:
  push:
    paths:
      - '**.tex'  # Runs when any .tex file is pushed
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install TeX Live
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-full

      - name: Compile LaTeX Files
        run: |
          find . -name "*.tex" -print0 | while IFS= read -r -d '' file; do
            dir=$(dirname "$file")
            filename=$(basename "$file" .tex)
            echo "Compiling $file..."
            pdflatex -output-directory="$dir" "$file"
          done

      - name: Push PDFs to Repository
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add **/*.pdf
          git commit -m "Auto-compiled PDFs"
          git push origin main
